### ISSUE TITLE
not working on raspberrypiOS 32 bit

### ISSUE THREAD

**Issue by Micha-123** [chrisb2/pi_ina219#36]
New RaspberryPI os,

installed python3
installed library

sudo pip3 install pi-ina219

that is installed successfuly but if i wil run the code 

` python ina219.py
Traceback (most recent call last):
  File "/home/pi/ina219.py", line 3, in <module>
    from ina219 import INA219
  File "/home/pi/ina219.py", line 3, in <module>
    from ina219 import INA219
ImportError: cannot import name 'INA219' from partially initialized module 'ina219' (most likely due to a circular import) (/home/pi/ina219.py)
`

**Comment by chrisb2** [comment]
You seem to have an ina219.py file in your home directory, I think you should delete this. If it's your test code which interacts with the library rename it to something like test.py.

Chris
